#!/usr/bin/env python3
"""
Ansh-108 Core — A-PQC : NIST KAT cross-check (the gold-standard interop)
=======================================================================
Verifies the OFFICIAL Falcon-512 Known-Answer-Test vectors with the chip-NTT
verifier + host codec. These signatures were generated by the Falcon reference's
NIST `crypto_sign` API (the canonical PQC test vectors) — entirely independent of
this project. Every genuine KAT signature must ACCEPT; tampering must REJECT.

Vector file: `falcon512-KAT.rsp` (NIST PQCsignKAT format, 100 records).
Provenance:  Falcon submission KAT, mirrored at github.com/QubitEthereum/falcon
             (KAT/falcon512-KAT.rsp). Integrity: sha256 printed below and pinned
             in the writeup. Authenticity is self-evidencing: an INDEPENDENT
             verifier (already validated vs the Prest reference) accepts all 100
             and rejects tampering, which only genuine Falcon signatures can do.

Pipeline per record (no network, no reference code):
    pk(897B, FIPS modq_encode) -> decode_public_key (chip codec)
    sm -> parse_nist_signed_message -> (msg, nonce, s2)   (chip codec)
    c = HashToPoint(nonce || msg)  (SHAKE-256 reject->=5q)
    s1 = c - s2*h    (s2*h on the chip's 12289 negacyclic NTT)
    accept iff ||(s1,s2)||^2 <= 34034726

Run:  python apqc_kat_check.py
"""
import sys
import os
import hashlib

ART = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ART)
from apqc_falcon_codec import decode_public_key, parse_nist_signed_message
from apqc_falcon_verify import verify, BETA2

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

KAT = os.path.join(ART, "falcon512-KAT.rsp")


def parse_records(raw):
    recs, cur = [], {}
    for line in raw.decode().splitlines():
        line = line.strip()
        if line.startswith("count ="):
            if cur:
                recs.append(cur)
            cur = {}
        if "=" in line:
            k, v = line.split("=", 1)
            cur[k.strip()] = v.strip()
    if cur:
        recs.append(cur)
    return recs


def main():
    fails = 0

    def check(name, cond):
        nonlocal fails
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}")
        if not cond:
            fails += 1

    print("A-PQC Falcon-512 NIST KAT cross-check (chip-NTT verifier)")
    raw = open(KAT, "rb").read()
    print(f"  KAT sha256: {hashlib.sha256(raw).hexdigest()}")
    recs = parse_records(raw)
    print(f"  records: {len(recs)}")

    accepted = 0
    msg_ok = True
    for r in recs:
        pk = bytes.fromhex(r["pk"])
        sm = bytes.fromhex(r["sm"])
        msg = bytes.fromhex(r["msg"])
        mlen = int(r["mlen"])
        h = decode_public_key(pk)
        pmsg, nonce, s2 = parse_nist_signed_message(sm, mlen)
        msg_ok &= (pmsg == msg)
        ok, nrm = verify(msg, (nonce, s2), h)
        if ok and nrm <= BETA2[512]:
            accepted += 1

    check(f"all {len(recs)} KAT messages recovered from sm", msg_ok)
    check(f"chip-NTT verifier ACCEPTS all {len(recs)} genuine KAT signatures "
          f"({accepted}/{len(recs)})", accepted == len(recs))

    # negative control: tamper the message of record 0 -> must reject
    r = recs[0]
    pk = bytes.fromhex(r["pk"]); sm = bytes.fromhex(r["sm"]); mlen = int(r["mlen"])
    h = decode_public_key(pk)
    msg, nonce, s2 = parse_nist_signed_message(sm, mlen)
    ok_t, _ = verify(msg + b"\x00", (nonce, s2), h)
    check("tampered KAT message REJECTS", not ok_t)

    print(f"\n{'ALL PASS' if fails == 0 else str(fails) + ' FAILURE(S)'}")
    return 0 if fails == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
